-------------------------------------
------- Created by T1GER#9080 -------
-------------------------------------

Lang = {
  -- CHAT MESSAGES:
  ['dispatch_name']           = '^5 Dispatch: ',
  ['police_notification1']    = '^0^*Armed^r Grand Theft Auto at ^3%s^0 | ^6^*Make: ^0^*%s | ^6Plate: ^0^*%s | ^6Colors: ^0^*%s ^6on ^0^*%s',
  ['police_notification2']    = '^0Grand Theft Auto at ^3%s^0 | ^6^*Make: ^0^*%s | ^6Plate: ^0^*%s | ^6Colors: ^0^*%s ^6on ^0^*%s',
  ['alarm_central']           = '^5 Alarm Central: ',
  ['vehicle_alarm_triggered'] = '^0Your vehicle [%s] alarm has been triggered at ^3%s^0',

  -- MENU STRINGS:
  ['button_yes']           	  = 'Oui',
  ['button_no']           	  = 'Non',
  ['shop_main_title']         = 'Sélectionnez un véhicule',
  ['reg_key_title']           = 'Prix de la clé: $%s',
  ['reg_alarm_title']         = 'Acheter Alarme: $%s',
  ['your_current_keys']       = 'Vos Clés Actuelles',
  ['keys_actions_title']      = 'Action des clés [%s]',
  ['give_key_menu']           = 'Donnez des Clés',
  ['remove_key_menu']         = 'Supprimer les Clés',
  ['delete_key_menu']         = 'Supprimer les Clés',
  ['car_interaction_title']   = 'Menu d\'Interaction de Voiture',
  ['keys_mangement_label']    = 'Gestion des Clés',
  ['veh_windows_label']       = 'Options des fenetre',
  ['veh_door_label']          = 'Options de Portes',
  ['veh_engine_label']        = 'Marche/Arrêt du moteur',
  ['veh_neon_label']          = 'Néon Marche / Arrêt',
  ['insurance_label']         = 'Véhicules Assurés',
  ['windows_menu_title']      = 'Fenêtres Haut / Bas',
  ['window_front_r']       		= 'Fenêtre avant (D)',
  ['window_front_l']       		= 'Fenêtre avant (G)',
  ['window_rear_r']       		= 'Lunette arrière (D)',
  ['window_rear_l']       		= 'Lunette arrière (G)',
  ['doors_menu_title']        = 'Ouvrir / Fermer Porte',
  ['door_hood']      			    = 'Capau',
  ['door_trunk']       			  = 'Coffre',
  ['door_front_l']            = 'Porte Avant (G)',
  ['door_front_r']            = 'Porte Avant (D)',
  ['door_rear_l']             = 'Porte Arriere (G)',
  ['door_rear_r']             = 'Porte Arriere (D)',

  -- NOTIFICATIONS:
  ['check_f8_console']        = '~r~VÉRIFIER LA CONSOLE F8!!!~s~',
  ['not_enough_money']        = 'Vous n\'avez pas assez d\'argent.',
  ['no_players_nearby']       = 'Aucun joueur à proximité.',
  ['no_veh_nearby']           = 'Aucun véhicule à proximité.',
  ['no_owned_vehicles']       = 'Vous n\'avez aucun ~r~véhicule~w~ en votre possession.',
  ['engine_not_running']      = 'Le moteur doit tourner!',
  ['must_be_inside_veh']      = 'Vous devez être à l\'intérieur d\'un véhicule!',
  ['must_be_driver_of_veh']   = 'Vous devez être dans le siège conducteur du véhicule!',
  ['veh_must_be_unlocked']    = 'Le véhicule doit être déverrouillé.',
  ['no_veh_in_direction']     = 'Aucun véhicule dans cette direction.',
  ['vehicle_locked']          = 'Vous avez <span style="color:red"><b>verrouillé</b></span> votre véhicule',
  ['vehicle_unlocked']        = 'Vous avez <span style="color:green"><b>déverrouillé</b></span> votre véhicule',
  ['has_key_false']         	= 'Vous n\'avez pas de clés pour cette voiture',
  ['all_veh_has_keys']        = 'Vous avez enregistré les clés de tous vos véhicules.',
  ['key_reg_accepted']        = 'Vous avez enregistré une nouvelle paire de clés pour le véhicule sélectionné.',
  ['all_veh_have_alarm']      = 'Vous disposez d\'une alarme pour tous vos véhicules.',
  ['alarm_aquired']           = 'Vous avez obtenu une alarme pour le véhicule sélectionné.',
  ['no_registerd_keys']       = 'Vous n\'avez pas de clés enregistrées à afficher',
  ['keys_received1']          = 'Vous avez reçu une paire de clés pour un véhicule <span style="color:blue">[%s].',
  ['keys_received2']          = 'Vous <span style="color:green"> avez reçu </span> une paire de clés pour un véhicule <span style="color:blue">[%s]</span> <span style="color:white ">de </span><span style="color:green">%s.</span>',
  ['u_gave_keys']             = 'Vous avez donné des clés [%s] de %s',
  ['u_removed_a_key']         = 'Vous avez supprimé les clés [%s] de %s',
  ['u_had_a_key_removed']     = 'Vos clés [%s] ont été supprimées par %s',
  ['target_has_no_key_copy']  = '%s n\'a pas de copie de cette clé...',
  ['couldnt_find_keys']       = 'Impossible de trouver les clés du véhicule / plaque : <span style="color:blue">%s',
  ['keys_deleted']            = 'Les clés de %s [%s] ont été supprimées.',
  ['engine_toggled_on']       = 'Vous avez <span style="color:green">allumé</span> le moteur du véhicule',
  ['engine_toggled_off']      = 'Vous avez <span style="color:red">éteint</span> le moteur du véhicule',
  ['npc_ran_away']      		  = 'Le PNJ s\'est enfui avec les clés',
  ['already_lockpicking']     = 'Vous êtes déjà en train de crocheter un véhicule!',
  ['move_closer_to_lockpick'] = 'Rapprochez-vous du véhicule lockpick.',
  ['first_check_if_locked']   = 'Veuillez vérifier si les véhicules sont verrouillés ou non...',
  ['deny_lockpick_unlocked']  = 'Vous ne pouvez pas verrouiller un véhicule qui n\'est pas verrouillé..',
  ['veh_lockpicked_success']  = 'Vous <span style="color:yellow">crocheter</span> le véhicule ....',
  ['veh_lockpicked_fail']     = 'Tu as <span style="color:red"> échoué </span><span style="color:yellow">à crocheter </span> le véhicule.',
  ['deny_hotwire']            = 'Le véhicule ne nécessite pas d\'être câblé à chaud.',
  ['hotwire_the_vehicle']     = 'Câblez à chaud le véhicule pour allumer le moteur.',
  ['already_hotwiring']       = 'Vous êtes déjà en train de câbler un véhicule à chaud!',
  ['veh_hotwire_success']     = 'Vous câblé le véhicule.',
  ['veh_hotwire_fail']        = 'Vous avez échoué à ~y~hotwire le véhicule.',
  ['already_searching']       = 'Vous êtes déjà à la recherche d\'un véhicule!',
  ['stop_the_vehicle']        = 'Veuillez d\'abord arrêter le véhicule!',
  ['cannot_search_car']       = 'Cette voiture est vide, ne vous embêtez même pas!',
  ['cash_found_x']      		  = 'Vous avez trouvé $%s en espèces.',
  ['item_found_x']      			= 'Vous avez trouvé %s x%s.',



  -- DRAW TEXTS:
  ['draw_locksmith']          = '~r~[E]~s~ Serrurier',
  ['draw_alarmshop']          = '~r~[E]~s~ Magasin d\'Alarme',

  -- PROGRESSBARS:
  ['progbar_talking']         = 'Parle au PNJ',
  ['progbar_searching']       = 'RECHERCHE',
  ['progbar_hotwiring']       = 'CÂBLAGE À CHAUD',
  ['progbar_lockpicking']     = 'CROCHETAGE',

  -- BLIPS:
  ['blip_locksmith']          = 'Serrurier',
  ['blip_alarmshop']          = 'Magasin d\'Alarme',
}
