name: Deployement 🚀

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 141.94.96.205
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_MDP }}
          script: |
            cd /home/CitizenRP
            git status
            git add .
            git stash
            git stash clear
            git remote update
            git pull origin main
            git status
